name: ci pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Permissão necessária para publicar no GHCR
permissions:
  contents: read
  packages: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - name: install the dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest httpx

      - name: run tests
        run: |
          pytest

  kustomize-lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: lint staging kustomize
        run: kustomize build overlays/staging

      - name: lint production kustomize
        run: kustomize build overlays/production

  build-and-push:
    needs: [run-tests, kustomize-lint]
    runs-on: ubuntu-latest
    steps:
      - name: checkou code
        uses: actions/checkout@v5

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e push da imagem
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}